# Assignment 4
> Dominik Huffield <br>
CS 533

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('compas-scores-two-years.csv')

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7214 entries, 0 to 7213
Data columns (total 53 columns):
id                         7214 non-null int64
name                       7214 non-null object
first                      7214 non-null object
last                       7214 non-null object
compas_screening_date      7214 non-null object
sex                        7214 non-null object
dob                        7214 non-null object
age                        7214 non-null int64
age_cat                    7214 non-null object
race                       7214 non-null object
juv_fel_count              7214 non-null int64
decile_score               7214 non-null int64
juv_misd_count             7214 non-null int64
juv_other_count            7214 non-null int64
priors_count               7214 non-null int64
days_b_screening_arrest    6907 non-null float64
c_jail_in                  6907 non-null object
c_jail_out                 6907 non-null object
c_case_number              7192 non-null object
c_offense_date             6055 non-null object
c_arrest_date              1137 non-null object
c_days_from_compas         7192 non-null float64
c_charge_degree            7214 non-null object
c_charge_desc              7185 non-null object
is_recid                   7214 non-null int64
r_case_number              3471 non-null object
r_charge_degree            3471 non-null object
r_days_from_arrest         2316 non-null float64
r_offense_date             3471 non-null object
r_charge_desc              3413 non-null object
r_jail_in                  2316 non-null object
r_jail_out                 2316 non-null object
violent_recid              0 non-null float64
is_violent_recid           7214 non-null int64
vr_case_number             819 non-null object
vr_charge_degree           819 non-null object
vr_offense_date            819 non-null object
vr_charge_desc             819 non-null object
type_of_assessment         7214 non-null object
decile_score.1             7214 non-null int64
score_text                 7214 non-null object
screening_date             7214 non-null object
v_type_of_assessment       7214 non-null object
v_decile_score             7214 non-null int64
v_score_text               7214 non-null object
v_screening_date           7214 non-null object
in_custody                 6978 non-null object
out_custody                6978 non-null object
priors_count.1             7214 non-null int64
start                      7214 non-null int64
end                        7214 non-null int64
event                      7214 non-null int64
two_year_recid             7214 non-null int64
dtypes: float64(4), int64(16), object(33)
memory usage: 2.9+ MB

In [4]:
df = data.loc[:,['age', 'c_charge_degree', 'race', 'age_cat', 'score_text', 'sex', 'priors_count', 
            'days_b_screening_arrest', 'decile_score', 'v_decile_score', 'is_recid', 'is_violent_recid', 'two_year_recid', 
            'c_jail_in', 'c_jail_out']]
df.head()

,age,c_charge_degree,race,age_cat,score_text,sex,priors_count,days_b_screening_arrest,decile_score,v_decile_score,is_recid,is_violent_recid,two_year_recid,c_jail_in,c_jail_out
0,69,F,Other,Greater than 45,Low,Male,0,-1.0,1,1,0,0,0,2013-08-13 06:03:42,2013-08-14 05:41:20
1,34,F,African-American,25 - 45,Low,Male,0,-1.0,3,1,1,1,1,2013-01-26 03:45:27,2013-02-05 05:36:53
2,24,F,African-American,Less than 25,Low,Male,4,-1.0,4,3,1,0,1,2013-04-13 04:58:34,2013-04-14 07:02:04
3,23,F,African-American,Less than 25,High,Male,1,NaN,8,6,0,0,0,NaN,NaN
4,43,F,Other,25 - 45,Low,Male,2,NaN,1,1,0,0,0,NaN,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7214 entries, 0 to 7213
Data columns (total 15 columns):
age                        7214 non-null int64
c_charge_degree            7214 non-null object
race                       7214 non-null object
age_cat                    7214 non-null object
score_text                 7214 non-null object
sex                        7214 non-null object
priors_count               7214 non-null int64
days_b_screening_arrest    6907 non-null float64
decile_score               7214 non-null int64
v_decile_score             7214 non-null int64
is_recid                   7214 non-null int64
is_violent_recid           7214 non-null int64
two_year_recid             7214 non-null int64
c_jail_in                  6907 non-null object
c_jail_out                 6907 non-null object
dtypes: float64(1), int64(7), object(7)
memory usage: 845.5+ KB

In [6]:
df = df[df['days_b_screening_arrest'] <= 30]
df = df[df['days_b_screening_arrest'] >= -30]
df = df[df['is_recid'] != -1]
df = df[df['c_charge_degree'] != 'O']
df = df[df['score_text'] != 'N/A']
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6172 entries, 0 to 7213
Data columns (total 15 columns):
age                        6172 non-null int64
c_charge_degree            6172 non-null object
race                       6172 non-null object
age_cat                    6172 non-null object
score_text                 6172 non-null object
sex                        6172 non-null object
priors_count               6172 non-null int64
days_b_screening_arrest    6172 non-null float64
decile_score               6172 non-null int64
v_decile_score             6172 non-null int64
is_recid                   6172 non-null int64
is_violent_recid           6172 non-null int64
two_year_recid             6172 non-null int64
c_jail_in                  6172 non-null object
c_jail_out                 6172 non-null object
dtypes: float64(1), int64(7), object(7)
memory usage: 771.5+ KB